slack_app_token: xapp-...
slack_bot_token: xoxb-...

discord:
  token: ...
  guild_id: ...
  min_sync_roleid: ...

features_enabled:
  - live_archive
  - parrotmaker
  - gdrive
  - regex_responses

live_archive:
  archive_path: /var/opt/async-parrotbot/slack-archive

gdrive:
  slack_local_path: /var/opt/async-parrotbot/files
  slack_remote_path: parrotbot-gdrive:"999 Slack Staging"
  slack_remote_nice_name: 999 Slack Staging
  discord_local_path: /var/opt/async-parrotbot/files/discord
  discord_remote_path: parrotbot-gdrive:"998 Discord Staging"
  discord_remote_nice_name: 998 Discord Staging
  rclone_log_path: /var/log/async-parrotbot/rclone-log

log:
  command: journalctl -u async-parrotbot
