slack_app_token: xapp-...
slack_bot_token: xoxb-...

features_enabled:
  - live_archive
  - parrotmaker
  - gdrive

live_archive:
  archive_path: /var/opt/async-parrotbot/slack-archive

gdrive:
  local_path: /var/opt/async-parrotbot/files
  remote_path: parrotbot-gdrive:"999 Slack Staging"
  remote_nice_name: 999 Slack Staging
  rclone_log_path: /var/log/async-parrotbot/rclone-log

log:
  command: journalctl -u async-parrotbot
